### ISSUE TITLE
Update BART trees from a given state

### ISSUE THREAD

**Issue by zjg540066169** [rsparapa/bnptools#3]
Hello,

I am working on a project to utilize BART as a module within our MCMC model. In each iteration of the MCMC algorithm, our intention is to update BART once and subsequently update the other parameters. The outcome values to fit are changed in each iteration. We are interested in finding a solution to inherit BART's parameters from the previous iteration and utilize them as the initial state for BART in the next iteration. I wonder if there is any function to do this? Thank you so much! Really appreciated!

Best regards,
Jungang

**Comment by rsparapa** [comment]
Hi Jungang. This Issues Q&A is for the R packages found here. Since this question does not appear to be on tpoic, I am closing it without further comment. Rodney
