### ISSUE TITLE
transposition issue for mc.gbart

### ISSUE THREAD

**Issue by bachlaw** [rsparapa/bnptools#4]
Hello,

Thank you for the wonderful package.  I am consistently getting the following error when trying to use the `transposed=TRUE` option with `mc.gbart`:

```The length of y.train and the number of rows in x.train must be identical```

These two things are in fact identical on my dataset, and when I ran the examples at the bottom of the `mc.gbart` file, using `gbart` instead of the indicated `wbart`, I get the same error. To (hopefully) reproduce, you can run:

```bartFit = mc.gbart(x,y,nskip=5,ndpost=5, transposed = TRUE)``` 

Perhaps there is something missing in the transposition code that is not fully transposing the predictor matrix as intended?

Thanks!

**Comment by rsparapa** [comment]
Over time, the transposed argument has largely moved from a user's argument to an implementation argument.  In other words, the user would not typically set it to TRUE.  Try transposed=FALSE
